"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { CalendarDays, Check, Clock3, DollarSign, Plus, Repeat2, Search, Trash2, UserPlus, Users, WalletCards, X } from "lucide-react";

import { AppShell } from "@/components/layout/AppShell";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

type Weekday = "MON" | "TUE" | "WED" | "THU" | "FRI" | "SAT";
type Student = { id: string; firstName: string; lastName: string; yearLevel: number };
type Batch = { id: string; name: string; startDate: string; startTime: string; isRecurring: boolean; recurringDays: Weekday[]; endDate: string | null; feePerSession: number | null; billingMethod: "MONTHLY" | "FULL_TERM" | null; currency: string; feeSummary: { unpaidCount: number; overdueCount: number; overdueAmount: number }; students: { student: Student }[] };
type BatchForm = { name: string; startDate: string; startTime: string; isRecurring: boolean; recurringDays: Weekday[]; endDate: string; feePerSession: string; billingMethod: "MONTHLY" | "FULL_TERM" };

const weekdays: { value: Weekday; label: string }[] = [
  { value: "MON", label: "Mon" }, { value: "TUE", label: "Tue" }, { value: "WED", label: "Wed" },
  { value: "THU", label: "Thu" }, { value: "FRI", label: "Fri" }, { value: "SAT", label: "Sat" },
];
const emptyForm: BatchForm = { name: "", startDate: "", startTime: "", isRecurring: false, recurringDays: [], endDate: "", feePerSession: "", billingMethod: "FULL_TERM" };

export default function BatchesPage() {
  const [batches, setBatches] = useState<Batch[]>([]);
  const [students, setStudents] = useState<Student[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState("");
  const [reloadKey, setReloadKey] = useState(0);
  const [showCreate, setShowCreate] = useState(false);
  const [assignmentBatch, setAssignmentBatch] = useState<Batch | null>(null);
  const [deleteBatch, setDeleteBatch] = useState<Batch | null>(null);
  const [totals, setTotals] = useState({ totalOverdue: 0, currency: "AUD" });

  useEffect(() => {
    const controller = new AbortController();
    async function load() {
      setIsLoading(true); setError("");
      try {
        const response = await fetch("/api/batches", { signal: controller.signal });
        const result = await response.json();
        if (!response.ok) throw new Error(result.error || "Batches could not be loaded.");
        setBatches(result.batches); setStudents(result.students); setTotals(result.totals ?? { totalOverdue: 0, currency: "AUD" });
      } catch (loadError) {
        if (loadError instanceof Error && loadError.name !== "AbortError") setError(loadError.message);
      } finally { if (!controller.signal.aborted) setIsLoading(false); }
    }
    load(); return () => controller.abort();
  }, [reloadKey]);

  const assignedStudents = new Set(batches.flatMap((batch) => batch.students.map(({ student }) => student.id))).size;

  return <AppShell><div className="mx-auto max-w-[1240px] space-y-6">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-[30px] font-bold tracking-[-0.025em] text-[#10233f]">Batches</h1><p className="mt-1 text-sm text-slate-500">Create class schedules and organise students into batches.</p></div><Button className="h-10 self-start bg-blue-600 px-4 text-white hover:bg-blue-700" onClick={() => setShowCreate(true)} size="lg"><Plus /> Create batch</Button></div>

    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Summary icon={CalendarDays} label="Total batches" value={String(batches.length)} tone="bg-blue-100 text-blue-600" /><Summary icon={Repeat2} label="Recurring batches" value={String(batches.filter((batch) => batch.isRecurring).length)} tone="bg-emerald-100 text-emerald-600" /><Summary icon={Users} label="Students assigned" value={String(assignedStudents)} tone="bg-violet-100 text-violet-600" /><Summary icon={DollarSign} label="Total overdue" value={formatMoney(totals.totalOverdue, totals.currency)} tone="bg-rose-100 text-rose-600" /></div>

    {error ? <Card className="border-rose-200 bg-rose-50 py-10 text-center"><p className="font-semibold text-rose-700">{error}</p><Button className="mx-auto mt-4" onClick={() => setReloadKey((value) => value + 1)} variant="outline">Try again</Button></Card> : null}
    {!error && isLoading ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{[1,2,3].map((item) => <div className="h-64 animate-pulse rounded-xl bg-white" key={item} />)}</div> : null}
    {!error && !isLoading && batches.length === 0 ? <Card className="border-0 bg-white py-14 text-center shadow-[0_2px_5px_rgba(15,35,65,0.08)]"><span className="mx-auto grid size-14 place-items-center rounded-full bg-blue-50 text-blue-600"><CalendarDays /></span><h2 className="mt-4 text-lg font-bold text-[#10233f]">Create your first batch</h2><p className="mx-auto mt-2 max-w-sm text-sm text-slate-500">Set up a once-off class or a recurring weekly schedule, then assign students.</p><Button className="mx-auto mt-5 bg-blue-600 text-white hover:bg-blue-700" onClick={() => setShowCreate(true)}><Plus /> Create batch</Button></Card> : null}
    {!error && !isLoading && batches.length > 0 ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{batches.map((batch) => <BatchCard batch={batch} key={batch.id} onAssign={() => setAssignmentBatch(batch)} onDelete={() => setDeleteBatch(batch)} />)}</div> : null}

    {showCreate ? <CreateBatchModal onClose={() => setShowCreate(false)} onCreated={() => { setShowCreate(false); setReloadKey((value) => value + 1); }} /> : null}
    {assignmentBatch ? <AssignStudentsModal batch={assignmentBatch} students={students} onClose={() => setAssignmentBatch(null)} onSaved={() => { setAssignmentBatch(null); setReloadKey((value) => value + 1); }} /> : null}
    {deleteBatch ? <DeleteBatchModal batch={deleteBatch} onClose={() => setDeleteBatch(null)} onDeleted={() => { setDeleteBatch(null); setReloadKey((value) => value + 1); }} /> : null}
  </div></AppShell>;
}

function BatchCard({ batch, onAssign, onDelete }: { batch: Batch; onAssign: () => void; onDelete: () => void }) {
  const schedule = batch.isRecurring ? batch.recurringDays.map((day) => weekdays.find((item) => item.value === day)?.label).join(", ") : "Once-off";
  if (batch.students.length === 0 || !batch.feePerSession || !batch.billingMethod) return <BatchCardWithoutStudents batch={batch} onAssign={onAssign} onDelete={onDelete} schedule={schedule} />;
  return <Card className="gap-0 border-0 bg-white py-0 shadow-[0_2px_5px_rgba(15,35,65,0.08)]"><CardContent className="flex h-full flex-col px-5 py-5"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-bold text-[#10233f]">{batch.name}</h2><span className={batch.isRecurring ? "mt-2 inline-flex rounded-full bg-blue-50 px-2.5 py-1 text-[11px] font-bold text-blue-700" : "mt-2 inline-flex rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-bold text-slate-600"}>{batch.isRecurring ? "Recurring" : "Once-off"}</span></div><Button aria-label={`Delete ${batch.name}`} className="text-slate-400 hover:bg-rose-50 hover:text-rose-600" onClick={onDelete} size="icon" variant="ghost"><Trash2 className="size-4" /></Button></div><div className="mt-5 space-y-3 border-y border-slate-100 py-4"><p className="flex items-center gap-2 text-sm text-slate-600"><CalendarDays className="size-4 text-slate-400" /><span className="font-semibold text-[#10233f]">{schedule}</span></p><p className="flex items-center gap-2 text-sm text-slate-600"><Clock3 className="size-4 text-slate-400" />{formatTime(batch.startTime)}</p><p className="text-xs text-slate-500">Starts {formatDate(batch.startDate)}{batch.endDate ? ` · Ends ${formatDate(batch.endDate)}` : ""}</p></div><div className="mt-4 flex-1"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Students</p><span className="text-xs font-bold text-[#10233f]">{batch.students.length}</span></div>{batch.students.length > 0 ? <div className="mt-3 flex flex-wrap gap-2">{batch.students.slice(0, 4).map(({ student }) => <span className="rounded-full bg-slate-50 px-2.5 py-1 text-[11px] font-semibold text-slate-600" key={student.id}>{student.firstName} {student.lastName}</span>)}{batch.students.length > 4 ? <span className="rounded-full bg-slate-50 px-2.5 py-1 text-[11px] font-semibold text-slate-500">+{batch.students.length - 4} more</span> : null}</div> : <p className="mt-3 text-xs text-slate-400">No students assigned yet.</p>}<div className="mt-4 rounded-lg bg-slate-50 px-3 py-2.5"><div className="flex items-center justify-between text-xs"><span className="font-semibold text-slate-500">Unpaid</span><span className="font-bold text-[#10233f]">{batch.feeSummary.unpaidCount}</span></div><div className="mt-1 flex items-center justify-between text-xs"><span className="font-semibold text-rose-600">Overdue</span><span className="font-bold text-rose-700">{batch.feeSummary.overdueCount} · {formatMoney(batch.feeSummary.overdueAmount, totalsCurrency(batch))}</span></div></div></div><div className="mt-5 grid grid-cols-2 gap-2"><Button className="h-9 border-slate-200 text-blue-700" onClick={onAssign} variant="outline"><UserPlus /> Assign</Button><Button className="h-9 bg-blue-600 text-white hover:bg-blue-700" nativeButton={false} render={<Link href={`/batches/${batch.id}/fees`} />}><WalletCards /> Manage fees</Button></div></CardContent></Card>;
}

function BatchCardWithoutStudents({ batch, schedule, onAssign, onDelete }: { batch: Batch; schedule: string; onAssign: () => void; onDelete: () => void }) {
  return <Card className="gap-0 border-0 bg-white py-0 shadow-[0_2px_5px_rgba(15,35,65,0.08)]"><CardContent className="flex h-full flex-col px-5 py-5"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-bold text-[#10233f]">{batch.name}</h2><span className={batch.isRecurring ? "mt-2 inline-flex rounded-full bg-blue-50 px-2.5 py-1 text-[11px] font-bold text-blue-700" : "mt-2 inline-flex rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-bold text-slate-600"}>{batch.isRecurring ? "Recurring" : "Once-off"}</span></div><Button aria-label={`Delete ${batch.name}`} className="text-slate-400 hover:bg-rose-50 hover:text-rose-600" onClick={onDelete} size="icon" variant="ghost"><Trash2 className="size-4" /></Button></div><div className="mt-5 space-y-3 border-y border-slate-100 py-4"><p className="flex items-center gap-2 text-sm text-slate-600"><CalendarDays className="size-4 text-slate-400" /><span className="font-semibold text-[#10233f]">{schedule}</span></p><p className="flex items-center gap-2 text-sm text-slate-600"><Clock3 className="size-4 text-slate-400" />{formatTime(batch.startTime)}</p><p className="text-xs text-slate-500">Starts {formatDate(batch.startDate)}{batch.endDate ? ` · Ends ${formatDate(batch.endDate)}` : ""}</p></div><div className="mt-4 flex-1"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Students</p><span className="text-xs font-bold text-[#10233f]">0</span></div><p className="mt-3 text-xs text-slate-400">Assign at least one student to manage fees.</p><div className="mt-4 rounded-lg bg-slate-50 px-3 py-2.5 text-xs font-semibold text-slate-500">Fee: {batch.feePerSession ? `${formatMoney(batch.feePerSession, batch.currency)} per session · ${batch.billingMethod === "MONTHLY" ? "Monthly" : "Full term"}` : "Not configured"}</div></div><div className="mt-5 grid grid-cols-2 gap-2"><Button className="h-9 border-slate-200 text-blue-700" onClick={onAssign} variant="outline"><UserPlus /> Assign</Button><Button className="h-9" disabled><WalletCards /> Manage fees</Button></div></CardContent></Card>;
}

function DeleteBatchModal({ batch, onClose, onDeleted }: { batch: Batch; onClose: () => void; onDeleted: () => void }) {
  const [isDeleting, setIsDeleting] = useState(false); const [error, setError] = useState("");
  async function remove() { setIsDeleting(true); setError(""); try { const response = await fetch(`/api/batches/${batch.id}`, { method: "DELETE" }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "The batch could not be deleted."); onDeleted(); } catch (deleteError) { setError(deleteError instanceof Error ? deleteError.message : "The batch could not be deleted."); } finally { setIsDeleting(false); } }
  return <Modal title="Delete batch?" description="This action cannot be undone." onClose={onClose}><div className="px-6 py-5"><div className="flex gap-4 rounded-xl bg-rose-50 p-4"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-rose-100 text-rose-600"><Trash2 className="size-5" /></span><div><p className="text-sm font-bold text-[#10233f]">{batch.name}</p><p className="mt-1 text-sm leading-6 text-slate-600">The batch and its {batch.students.length} student assignment{batch.students.length === 1 ? "" : "s"} will be removed. Student records will not be deleted.</p></div></div>{error ? <div className="mt-4 rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div> : null}</div><div className="flex justify-end gap-2 border-t border-slate-100 px-6 py-4"><Button disabled={isDeleting} onClick={onClose} variant="outline">Cancel</Button><Button className="bg-rose-600 text-white hover:bg-rose-700" disabled={isDeleting} onClick={remove}><Trash2 />{isDeleting ? "Deleting..." : "Delete batch"}</Button></div></Modal>;
}

function CreateBatchModal({ onClose, onCreated }: { onClose: () => void; onCreated: () => void }) {
  const [form, setForm] = useState(emptyForm); const [error, setError] = useState(""); const [isSaving, setIsSaving] = useState(false);
  function toggleDay(day: Weekday) { setForm((current) => ({ ...current, recurringDays: current.recurringDays.includes(day) ? current.recurringDays.filter((item) => item !== day) : [...current.recurringDays, day] })); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setIsSaving(true); setError(""); try { const response = await fetch("/api/batches", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "The batch could not be created."); onCreated(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "The batch could not be created."); } finally { setIsSaving(false); } }
  return <Modal title="Create batch" description="Add the schedule and fee details; students can be assigned afterwards." onClose={onClose}>
    <form onSubmit={submit}>
      <div className="space-y-5 px-6 py-5">
        <Field label="Batch name" required><Input className="mt-2 h-10 border-slate-200" onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="e.g. Year 10 Advanced Maths" required value={form.name} /></Field>
        <div className="grid gap-5 sm:grid-cols-2"><Field label="Start date" required><Input className="mt-2 h-10 border-slate-200" onChange={(event) => setForm({ ...form, startDate: event.target.value })} required type="date" value={form.startDate} /></Field><Field label="Time" required><Input className="mt-2 h-10 border-slate-200" onChange={(event) => setForm({ ...form, startTime: event.target.value })} required type="time" value={form.startTime} /></Field></div>
        <label className="flex cursor-pointer items-start gap-3 rounded-xl border border-slate-200 p-4"><input checked={form.isRecurring} className="mt-0.5 size-4 accent-blue-600" onChange={(event) => setForm({ ...form, isRecurring: event.target.checked, recurringDays: event.target.checked ? form.recurringDays : [], endDate: event.target.checked ? form.endDate : "", billingMethod: event.target.checked ? "MONTHLY" : "FULL_TERM" })} type="checkbox" /><span><span className="block text-sm font-bold text-[#10233f]">Recurring batch</span><span className="mt-1 block text-xs text-slate-500">Repeat this batch on selected weekdays.</span></span></label>
        {form.isRecurring ? <div className="space-y-5"><Field label="Frequency" required><div className="mt-2 grid grid-cols-3 gap-2 sm:grid-cols-6">{weekdays.map((day) => <button className={form.recurringDays.includes(day.value) ? "h-10 rounded-lg bg-blue-600 text-xs font-bold text-white" : "h-10 rounded-lg border border-slate-200 text-xs font-semibold text-slate-600 hover:bg-slate-50"} key={day.value} onClick={() => toggleDay(day.value)} type="button">{day.label}</button>)}</div></Field><Field label="End date" required><Input className="mt-2 h-10 border-slate-200" min={form.startDate || undefined} onChange={(event) => setForm({ ...form, endDate: event.target.value })} required type="date" value={form.endDate} /></Field></div> : <div className="rounded-lg bg-slate-50 px-4 py-3 text-xs text-slate-500">This batch will occur once on the selected start date and time.</div>}
        <div className="border-t border-slate-100 pt-5"><p className="text-sm font-bold text-[#10233f]">Fee details</p><div className="mt-4 grid gap-5 sm:grid-cols-2"><Field label="Fee per session" required><Input className="mt-2 h-10 border-slate-200" min="0.01" onChange={(event) => setForm({ ...form, feePerSession: event.target.value })} placeholder="e.g. 30.00" required step="0.01" type="number" value={form.feePerSession} /></Field><Field label="Fee schedule" required><select className="mt-2 h-10 w-full rounded-md border border-slate-200 bg-white px-3 text-sm text-[#10233f] outline-none focus:border-blue-500" onChange={(event) => setForm({ ...form, billingMethod: event.target.value as BatchForm["billingMethod"] })} required value={form.billingMethod}><option value="FULL_TERM">Full term</option>{form.isRecurring ? <option value="MONTHLY">Monthly</option> : null}</select></Field></div><p className="mt-2 text-xs text-slate-500">Fees are calculated from scheduled sessions after each student joins.</p></div>
        {error ? <div className="rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div> : null}
      </div>
      <div className="flex justify-end gap-2 border-t border-slate-100 px-6 py-4"><Button disabled={isSaving} onClick={onClose} type="button" variant="outline">Cancel</Button><Button className="bg-blue-600 text-white hover:bg-blue-700" disabled={isSaving || !form.feePerSession || (form.isRecurring && (form.recurringDays.length === 0 || !form.endDate))} type="submit">{isSaving ? "Creating..." : <><Plus /> Create batch</>}</Button></div>
    </form>
  </Modal>;
}

function AssignStudentsModal({ batch, students, onClose, onSaved }: { batch: Batch; students: Student[]; onClose: () => void; onSaved: () => void }) {
  const [selected, setSelected] = useState(() => new Set(batch.students.map(({ student }) => student.id))); const [query, setQuery] = useState(""); const [error, setError] = useState(""); const [isSaving, setIsSaving] = useState(false);
  const visible = useMemo(() => students.filter((student) => `${student.firstName} ${student.lastName} Year ${student.yearLevel}`.toLowerCase().includes(query.toLowerCase().trim())), [students, query]);
  function toggle(id: string) { setSelected((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; }); }
  async function save() { setIsSaving(true); setError(""); try { const response = await fetch(`/api/batches/${batch.id}/students`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ studentIds: [...selected] }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Assignments could not be saved."); onSaved(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Assignments could not be saved."); } finally { setIsSaving(false); } }
  return <Modal title="Assign students" description={`${batch.name} · ${selected.size} selected`} onClose={onClose}><div className="px-6 py-5"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><Input className="h-10 border-slate-200 pl-9" onChange={(event) => setQuery(event.target.value)} placeholder="Search students..." value={query} /></div><div className="mt-4 flex items-center justify-between"><button className="text-xs font-bold text-blue-700" onClick={() => setSelected(new Set(students.map((student) => student.id)))} type="button">Select all</button><button className="text-xs font-semibold text-slate-500" onClick={() => setSelected(new Set())} type="button">Clear all</button></div><div className="mt-3 max-h-80 divide-y divide-slate-100 overflow-y-auto rounded-xl border border-slate-100">{visible.map((student) => <label className="flex cursor-pointer items-center gap-3 px-4 py-3 hover:bg-slate-50" key={student.id}><input checked={selected.has(student.id)} className="size-4 accent-blue-600" onChange={() => toggle(student.id)} type="checkbox" /><span className="grid size-9 place-items-center rounded-full bg-blue-100 text-[11px] font-bold text-blue-700">{student.firstName[0]}{student.lastName[0]}</span><span className="flex-1"><span className="block text-sm font-bold text-[#10233f]">{student.firstName} {student.lastName}</span><span className="text-xs text-slate-400">Year {student.yearLevel}</span></span>{selected.has(student.id) ? <Check className="size-4 text-blue-600" /> : null}</label>)}{students.length === 0 ? <div className="px-4 py-10 text-center"><p className="text-sm font-semibold text-[#10233f]">No active students available</p><p className="mt-1 text-xs text-slate-500">Approve a registration to create a student first.</p></div> : visible.length === 0 ? <p className="px-4 py-10 text-center text-sm text-slate-500">No matching students.</p> : null}</div>{error ? <div className="mt-4 rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div> : null}<p className="mt-4 text-xs leading-5 text-slate-500">Unchecked students will be removed from this batch when you save.</p></div><div className="flex justify-end gap-2 border-t border-slate-100 px-6 py-4"><Button disabled={isSaving} onClick={onClose} variant="outline">Cancel</Button><Button className="bg-blue-600 text-white hover:bg-blue-700" disabled={isSaving} onClick={save}>{isSaving ? "Saving..." : `Save ${selected.size} student${selected.size === 1 ? "" : "s"}`}</Button></div></Modal>;
}

function Modal({ title, description, onClose, children }: { title: string; description: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-slate-950/40 px-4 py-8" onMouseDown={onClose} role="presentation"><div aria-modal="true" className="w-full max-w-xl overflow-hidden rounded-2xl bg-white shadow-2xl" onMouseDown={(event) => event.stopPropagation()} role="dialog"><div className="flex items-start justify-between border-b border-slate-100 px-6 py-5"><div><h2 className="text-xl font-bold text-[#10233f]">{title}</h2><p className="mt-1 text-sm text-slate-500">{description}</p></div><button aria-label="Close" className="rounded-lg p-1 text-slate-400 hover:bg-slate-100" onClick={onClose}><X className="size-5" /></button></div>{children}</div></div>; }
function Field({ label, required, children }: { label: string; required?: boolean; children: React.ReactNode }) { return <label className="block"><span className="text-xs font-bold text-[#10233f]">{label}{required ? <span className="ml-1 text-rose-500">*</span> : null}</span>{children}</label>; }
function Summary({ icon: Icon, label, value, tone }: { icon: typeof CalendarDays; label: string; value: string; tone: string }) { return <Card className="gap-0 border-0 bg-white py-0 shadow-[0_2px_5px_rgba(15,35,65,0.08)]"><CardContent className="flex items-center gap-4 px-5 py-4"><span className={`grid size-10 place-items-center rounded-xl ${tone}`}><Icon className="size-5" /></span><div><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-[#10233f]">{value}</p></div></CardContent></Card>; }
function formatDate(value: string) { return new Intl.DateTimeFormat("en-AU", { day: "numeric", month: "short", year: "numeric", timeZone: "UTC" }).format(new Date(value)); }
function formatTime(value: string) { const [hours, minutes] = value.split(":").map(Number); return new Intl.DateTimeFormat("en-AU", { hour: "numeric", minute: "2-digit" }).format(new Date(2000, 0, 1, hours, minutes)); }
function formatMoney(value: number, currency: string) { return new Intl.NumberFormat("en-AU", { style: "currency", currency, maximumFractionDigits: 2 }).format(value); }
function totalsCurrency(batch: Batch) { return batch.currency; }
